command_timeout = 1000
right_format = """$time"""

[time]
disabled = false
style = "#939594"
format = "[$time]($style)"

[aws]
style = "bg:#5c5c5c fg:#e6e6e6"
symbol = "‚òÅ "
format = "[ÓÇ∞](fg:#e6e6e6 bg:#5c5c5c)[$symbol$profile]($style)[ÓÇ∞](fg:#f9a600 bg:black)"

[character]
success_symbol = "[‚ùØ](#e6e6e6)"
error_symbol = "[‚úó](#9a9a9a)"

[cmd_duration]
style = "#5c5c5c"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#5c5c5c)[Ô®ö$duration](bg:$style fg:#e6e6e6)[ÓÇ∞](fg:$style)"

[directory]
style = "#3a3a3a"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[ÓÇ∞](fg:#e6e6e6 bg:##3a3a3a)[$path[$read_only](bg:$style fg:#e6e6e6)](bg:$style fg:#e6e6e6)[ÓÇ∞](fg:$style)"
read_only = " ÔÄ£"

[docker_context]
style = "fg:#e6e6e6 bg:#6a6a6a"
symbol = "üê≥  "
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$context]($style)[ÓÇ∞](fg:#6a6a6a)"

[git_branch]
style = "#4a4a4a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:$style)[ $symbol$branch](fg:#e6e6e6 bg:$style)[ÓÇ∞](fg:$style)"

[git_commit]
style = "#4a4a4a"
format = "\b[ ](bg:$style)[\\($hash$tag\\)](fg:#e6e6e6 bg:$style)[ÓÇ∞](fg:$style)"

[git_state]
style = "#4a4a4a"
format = "\b[ ](bg:$style)[ \\($state( $progress_current/$progress_total)\\)](fg:#e6e6e6 bg:$style)[ÓÇ∞](fg:$style)"

[git_status]
style = "#4a4a4a"
format = "(\b[ ](bg:$style fg:#e6e6e6)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind[ÓÇ∞](fg:$style))"
conflicted = "[ÔÅ± ](bold fg:#e6e6e6 bg:#4a4a4a)[ ÔëÄ ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
staged = "[ÔÅß $count ](fg:#e6e6e6 bg:#4a4a4a)"
modified = "[Ô£™ ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
renamed = "[ÔÄ´ ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
deleted = "[ÔÄî ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
untracked = "[?${count} ](fg:#e6e6e6 bg:#4a4a4a)"
stashed = "[Ôíá ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
ahead = "[ÔÉÆ ${count} ](fg:#b0b0b0 bg:#4a4a4a)"
behind = "[ÔÉ≠ ${count} ](fg:#e6e6e6 bg:#4a4a4a)"
diverged = "[ÔÅ± ](fg:#e6e6e6 bg:#4a4a4a)[ Ô≠Ä ](fg:#e6e6e6 bg:#4a4a4a)[ÔÉÆ ${ahead_count} ](fg:#e6e6e6 bg:#4a4a4a)[ÔÉ≠ ${behind_count} ](fg:#e6e6e6 bg:#4a4a4a)"

[golang]
symbol = "Ô≥ë "
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[helm]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol($version)]($style)[ÓÇ∞](fg:#6a6a6a)"

[java]
symbol = "ÔÉ¥ "
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[kotlin]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[kubernetes]
format = "[ÓÇ∞](fg:#e6e6e6 bg:#2b2b2b)[$symbol$context](fg:#e6e6e6 bg:#2b2b2b)[ÓÇ∞](fg:#2b2b2b)"
disabled = false

#[memory_usage]
#style = "#5c5c5c"
#symbol = "Ôûô "
#format = "[ÓÇ∞](fg:#e6e6e6 bg:#5c5c5c)[$symbol$ram](bg:$style fg:#e6e6e6)[ÓÇ∞](fg:$style)"
#threshold = 95
#disabled = false

[nodejs]
style = "green"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol($version)](fg:#e6e6e6 bg:#6a6a6a)[ÓÇ∞](fg:#6a6a6a)"

[ocaml]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[package]
disabled = true

[php]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[python]
symbol = "Ô†† "
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$pyenv_prefix$version$virtualenv]($style)[ÓÇ∞](fg:#6a6a6a)"

[ruby]
symbol = "Óàû "
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version](fg:#e6e6e6 bg:#6a6a6a)(fg:#e6e6e6 bg:#6a6a6a)[ÓÇ∞](fg:#6a6a6a)"

[rust]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[scala]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[swift]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"

[shell]
fish_indicator = ""
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = ""
format = "[$indicator](fg:#e6e6e6)"
disabled = false
[shlvl]
symbol = "Ôïù‚Äâ"
style = "fg:#e6e6e6 bg:#2b2b2b"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#2b2b2b)[$symbol$shlvl]($style)[ÓÇ∞](fg:#2b2b2b)"
disabled = false

[terraform]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$workspace]($style)[ÓÇ∞](fg:#6a6a6a)"

[username]
show_always = true
style_user = "#cfcfcf"
style_root = "#e6e6e6"
format = "[$user@](fg:#e6e6e6)"

[hostname]
ssh_only = false
format = "[$hostname](fg:#cfcfcf) "

[vagrant]
style = "fg:#e6e6e6 bg:#6a6a6a"
format = "[ÓÇ∞](fg:#e6e6e6 bg:#6a6a6a)[$symbol$version]($style)[ÓÇ∞](fg:#6a6a6a)"
